### ISSUE TITLE
Firebase Crashlytics Crash: Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled

### ISSUE THREAD

**Issue by AuroPick** [Netvent/storyly-sdk#357] opened 2024-04-24 07:17 UTC
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

Hi we are getting this firebase crashlyics error in production.
![image](https://github.com/Netvent/storyly-mobile/assets/53499802/34b941b9-220a-450d-a9f7-3be6920dda06)
`stacktrace`
```
Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.appsamurai.storyly.storylylist.StorylyListRecyclerView{6ded833 VFED..... ......ID 0,0-1016,0 #7f090228 app:id/st_storyly_list_recycler_view}, adapter:androidx.recyclerview.widget.e@d33c7f0, layout:com.appsamurai.storyly.storylylist.StorylyListRecyclerView$1@9977169, context:com.xxx.MainActivity@e94d49
       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:284)
       at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:22)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:27)
       at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:7)
       at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:3)
       at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:17)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:711)
       at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(:4)
       at android.animation.Animator.callOnList(Animator.java:669)
       at android.animation.Animator.notifyListeners(Animator.java:608)
       at android.animation.Animator.notifyEndListeners(Animator.java:633)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
       at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame()
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1658)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1669)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1188)
       at android.view.Choreographer.doFrame(Choreographer.java:1054)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1639)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at android.app.ActivityThread.main(ActivityThread.java:8594)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
```

## Environment Details
**Storyly SDK Version:** 2.4.0
**React Native SDK Version:** 0.72.6
**Platform:**
- [x] Android 
- [ ] iOS
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:**

## Steps to Reproduce

1.
2.
3.
4.

**Comment by levent-oral** [comment] 2024-05-30 12:51
Hello @AuroPick ,

We're unable to reproduce the issue. It likely occurs under rare conditions.

We've a similar issue reported us with same setup; Storyly SDK 2.4.0 and React-Native 0.72.6 and there is no other report from latest versions of Storyly SDK. Moreover, we've improvements related to this part of SDK. It's likely that the issue has been fixed in newer versions of Storyly.

Please update the [Storyly SDK latest version](https://github.com/Netvent/storyly-sdk/blob/master/react-native/storyly-react-native/RELEASENOTES.md#301-30052024) and let us know the issue persists.

Thanks!

**Closed by levent-oral** 2024-05-30 12:51 UTC
Labels: bug, react native, in progress
